### ISSUE TITLE
First PR Capstone Project JS

### ISSUE THREAD

**Issue by VelzckC0D3** [VelzckC0D3/JavaScript-Captsone#52]
# Capstone Project JavaScript Module -  `WebPack` `ES6` `API`

## ✨ _Requested Implementations_ ✨
✔️ _Prepared the project with my only coding partner @MarcoDDM_
✔️ _Followed the steps described in the provided article `curriculum-tools-copy-projects`_
✔️ _Double-checked that we can see all the cards `Student A` `Student B` & `Student C`_
✔️ _Checked that the cards starts with `[Xpt]`  the number of points for each step_
✔️ _Removed all the `Stuent C` tasks since it's only a 2 people team_
✔️ _All tasks are assigned equally to the team members_
✔️ _Opened a new Issue with all the requirements

✔️ _Here's the Kanban project link https://github.com/VelzckC0D3/JavaScript-Captsone/projects/3_

#  💡 _Thank you for your review!_ 💡

**Comment by prolajumokeoni** [comment]
Hello @VelzckC0D3, Kindly add a link to your Github project(kanban board) above ⬆️

**Comment by VelzckC0D3** [comment]
> Hello @VelzckC0D3 and @MarcoDDM , Kindly add a link to your Github project(kanban board) in the issue above ⬆️

@prolajumokeoni  Done!, thank you

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
